[listener]
type="socket"

[service.sshauth]
type="ssh-auth"

[[port]]
port="tcp/2222"
services=["sshauth"]

[service.ethereum]
type="ethereum"

[[port]]
port="tcp/8545"
services=["ethereum"]

[service.vnc]
type="vnc"
image="/data/images/desktop.png"
server-name="WS-3244"

[[port]]
port="tcp/5900"
services=["vnc"]
[service.smtp]
type="smtp"

[[port]]
port="tcp/25"
services=["smtp"]

[service.adb01]
type="adb"

[[port]]
port="tcp/5037"
services=["adb01"]

[service.dns01]
type="dns"

[[port]]
port="udp/53"
services=["dns01"]

[service.ipp]
type="ipp"
server="HP LaserJet"
storage-dir="/tmp/"

[[port]]
port="tcp/631"
services=["ipp"]

[service.ldap]
type="ldap"
credentials=["admin:admin", "root:root"]
naming-contexts=[ "dc=example,dc=com", "dc=ad,dc=myserver,dc=com" ]
vendor-name=[ "HT Directory Server" ]
vendor-version=[ "0.1.0.0" ]
description=[ "Directory Server" ]
objectclass=[ "dcObject", "organization" ]

[[port]]
port="tcp/389" #or udp
services=["ldap"]

[service.memcached01]
type="memcached"

[[port]]
port="udp/11211"
services=["memcached01"]

[service.redis]
type="redis"
version="4.0.2"
os="Linux 2.6.32-431.el6.x86_64 x86_64"

[[port]]
port="tcp/6379"
services=["redis"]

[channel.file]
type="file"
filename="/home/honeytrap.log"

[[filter]]
channel=["file"]

[[logging]]
output = "stdout"
level = "info"
