[listener]
type="socket"

[service.sshauth]
type="ssh-auth"

[[port]]
port="tcp/2222"
services=["sshauth"]

[service.ethereum]
type="ethereum"

[[port]]
port="tcp/8545"
services=["ethereum"]

[service.vnc]
type="vnc"
image="/data/images/desktop.png"
server-name="WS-3244"

[[port]]
port="tcp/5900"
services=["vnc"]
[service.smtp]
type="smtp"

[[port]]
port="tcp/25"
services=["smtp"]

[channel.file]
type="file"
filename="/home/honeytrap.log"

[[filter]]
channel=["file"]

[[logging]]
output = "stdout"
level = "debug"
